# Basic statistics 
 

## anova operator

##### Description
`anova` operator performs an analaysis of variance of the data

##### Usage
Input projection|.
:---|:---
`color`   | represents the groups to compare
`y-axis`| measurement value

Output relations|.
:---|:---
`pr`| numeric, p-value calculated per cell

##### Details
`anova` operator performs an analaysis of variance of the data


##### References
see https://en.wikipedia.org/wiki/Analysis_of_variance


##### See Also
[ttest](https://github.com/tercen/ttest_operator), [rfImp](https://github.com/tercen/rfImp_operator)

##### Examples




##### GitHub link

[anova_operator on GitHub](https://github.com/tercen/anova_operator) 

## asinh operator

##### Description
`asinh` operator performs an inverse hyperbolic sine on values

##### Usage
Input projection|.
:---|:---
`y-axis` | values required to be transformed by the asinh operator
`row`    | channels, and scale values (optional)
`col`    | event, for example

Input parameters|.
:---|:---
`scale`  | numeric, the scaling factor to use before the asinh transformation, a NULL value indicates different scaling values per channel, default is 5

Output relations|.
:---|:---
`asinh`| numeric, output transformation per `row` and `col`.

##### Details
Values are scaled first and then asinh transformation is performed. One data point per cell is required as input. 
```r
asinh(value/scale)
```
A scale of 5 is recommended for cytof measurement and 150 for flowcyto measurements.

if a NULL scaling value is used then the scaling factor is give by the input cross-tab projection, the second factor defined in the `row` dimension indicates the scaling values to use per channel.


##### References
see the `base::asinh` function of the R package for the documentation,
https://en.wikipedia.org/wiki/Inverse_hyperbolic_functions


##### See Also

##### Examples


##### GitHub link

[asinh_operator on GitHub](https://github.com/tercen/asinh_operator) 

## basechange operator

##### Description
`basechange` operator performs a basechange calculation of a base value compared to a given data point.

##### Usage
Input projection|.
:---|:---
`y-axis`,`layer1`| data point to be compared with base
`y-axis`,`layer2`| base value

Input parameters|.
:---|:---
`percentage`   | logical, indicates if the basechange is retuend as a percentage

Output relations|.
:---|:---
`basechange`| numeric, basechange value, per cell


##### Details
`basechange` operator performs a basechange calculation of a base value compared to a given data point.

##### References

##### See Also


##### Examples


##### GitHub link

[basechange_operator on GitHub](https://github.com/tercen/basechange_operator) 

## Setup packrat 

```R
packrat::init(options = list(use.cache = TRUE))
```

```R
shiny::runApp(port=3044, launch.browser = TRUE)
```

 







##### GitHub link

[cellplot_shiny_operator on GitHub](https://github.com/tercen/cellplot_shiny_operator) 

## constant operator

##### Description
`constant` operator allows for a value equal to a constant to be generated

##### Usage
Input projection|.
:---|:---
none |

Input parameters|.
:---|:---
`value` | numeric, the constant value to be generated, default is 0

Output relations|.
:---|:---
`constant`| numeric, one constant is generated per cell

##### Details
A `constant` value is generated for all the data. All factors are therefore associated with this constant. A typical use of this operator is when you require to generate fixed boundary values to be used as a grid line in a later (i.e. downstream) step. The grid line is created in a `layer` using the `h-grid view type`. An example would be to create a zero grid line, where the`constant`operator is used to generate a zero value and a zero line is then available for later visuals.

##### References

##### See Also

##### Examples

https://tercen.com/operator/p/8d8febb97ed4b09c2ddf52795c961e68


 
 


##### GitHub link

[constant_operator on GitHub](https://github.com/tercen/constant_operator) 

## count operator

##### Description
`count` operator counts the number of data points.

##### Usage

Input projection|.
:---|:---
`y-axis`        | is the input data to be counted, per cell 

Output relations|.
:---|:---
`count`          | numeric, count of the input values

##### Details
The operator takes all the values of a cell and counts them. The computation is done per cell. There is one value calculated and returned for each of the input cell.

##### References


##### See Also

[product](https://github.com/tercen/product_operator), [sum](https://github.com/tercen/sum_operator)


##### Examples


##### GitHub link

[count_operator on GitHub](https://github.com/tercen/count_operator) 

## cv operator

##### Description
`cv` operator calculates the coefficient of variance on a set of input values.

##### Usage
Input projection|.
:---|:---
`y-axis`| values to be used for the calculation of the cv, per cell


Output relations|.
:---|:---
`cv`| numeric, coefficient of variation result per cell

##### Details
The coefficcient of variation is a measure of variaton, it is equivalent to standard deviation divided by the mean.
```r
cv = sd/mean
```
The `cv` is returned as a fraction.

##### References
see the https://en.wikipedia.org/wiki/Coefficient_of_variation


##### See Also
[sd](https://github.com/tercen/sd_operator), [mean](https://github.com/tercen/mean_operator)

##### Examples




##### GitHub link

[cv_operator on GitHub](https://github.com/tercen/cv_operator) 

### Cytonorm operator

##### Description

The `Cytonorm` operator normalizes cytometry data between mutliple batches.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell 

Output relations|.
:---|:---
`value`        | numeric, median of the input data

##### Details


##### References

https://github.com/saeyslab/CytoNorm

##### See Also

[flowsom_operator](https://github.com/tercen/flowsom_operator)
[flowai_operator](https://github.com/tercen/flowai_operator)


##### GitHub link

[cytonorm_operator on GitHub](https://github.com/tercen/cytonorm_operator) 

## density operator

##### Description
`density` operator performs a density caculations on x and y input values.

##### Usage
Input projection|.
:---|:---
`x-axis`  | indicates the values of the x
`y-axis`  | indicates the values of the y

Output relations|.
:---|:---
`density`| numeric, density calculation, calculated per cell

##### Details
A density calculation is performed per cell with the input values defined by the x and y-axis, the result are `density` values associated with each cell. The `density` operator is typically used in a pairwise plot and the returned `density` values are usually used as a coloring in a pairwise plot of the original input values. 


##### References

##### See Also

##### Examples




 
 


##### GitHub link

[density_operator on GitHub](https://github.com/tercen/density_operator) 

## Fast t-SNE Docker Operator

## Build the image

```bash
VERSION=0.0.1
docker build -t tercen/fast_tSNE_docker_operator:$VERSION .
docker push tercen/fast_tSNE_docker_operator:$VERSION
git add -A && git commit -m "$VERSION" && git tag  $VERSION  && git push && git push :--tags
```


##### GitHub link

[fast_tSNE_docker_operator on GitHub](https://github.com/tercen/fast_tSNE_docker_operator) 

## foldchange operator

##### Description
`foldchange` operator performs a fold change (i.e. ratio) caculation between two values.

##### Usage
Input projection|.
:---|:---
`x-axis`  | contains the grouping factor for the fold change calculation, 
`y-axis` | values

Input parameter|.
:---|:---
`reverse`  | logical, to reverse the calculation, default is `FALSE`


Output relations|.
:---|:---
`FoldChange`| numeric, foldchange, calculated per cell

##### Details
A foldchange operation is performed per cell. Each cell has values defined by the y-axis and seperated by the x-axis. The result of the foldchange is the ratio of the first divided by the second. If reverse is selected then the order of the ratio is changed.


##### References

##### See Also
[ratio](https://github.com/tercen/ratio_operator),[logfoldchange](https://github.com/tercen/logfoldchange_operator)
##### Examples




 
 


##### GitHub link

[foldchange_operator on GitHub](https://github.com/tercen/foldchange_operator) 

## eGFR operator

##### Description
`eGFR` operator calculates the glomerular filtration rate.


##### Usage
Input projection|.
:---|:---
`col` | 2nd factor age, 3rd factor gender
`y-axis, layer1`| is the value for serum creatine marker
`y-axis, layer2`| is the value for serum cystatin c marker


Output relations|.
:---|:---
`eGFR_0`| numeric, equation 0 calculation of the GFR estimate (e.g. per cell)
`eGFR_1`| numeric, equation 1 calculation of the GFR estimate (e.g. per cell)
`eGFR_2`| numeric, equation 2 calculation of the GFR estimate (e.g. per cell)
`eGFR_3`| numeric, equation 3 calculation of the GFR estimate (e.g. per cell)

##### Details
`gfr` operator estimates Glomerular filtration rate (GFR) is the best overall index of kidney function.
Four equations are used to calculate four eGFR values.

equation 0:
```r
    a <- ifelse (gender=="Female", -0.248, -0.207) 
    k <- ifelse (gender=="Female", 0.7, 0.9) 
    eGFR <-  135 * (min(crt/k, 1))^a * (max(crt/k, 1))^-0.601 * (min(cyt/0.8, 1))^-0.375 * (max(cyt/0.8, 1))^-0.711 * 0.995^age
    eGFR <- ifelse (gender=="Female",0.969 * eGFR, eGFR)
    eGFR <- ifelse (race=="Black",1.08 * eGFR, eGFR)
```

equation 1:
```r
    if (gender == "Female"){
           if   (crt <= 0.7) { eGFR <- 144 * (crt/ 0.7)^-0.329  * 0.995^age }
           if   (crt >  0.7) { eGFR <- 144 * (crt/ 0.7)^-1.209 * 0.995^age }
    }
    if (gender == "Male"){
           if   (crt <= 0.9) { eGFR <- 144 * (crt/ 0.9)^-0.411  * 0.995^age }
           if   (crt >  0.9) { eGFR <- 144 * (crt/ 0.9)^-1.209 * 0.995^age }
    }
    eGFR <- ifelse (race=="Black",1.159 * eGFR, eGFR)
```

equation 2:
```r
      if   (cyt <= 0.8) { eGFR <- 133 * (cyt/ 0.8)^-0.449 * 0.996^age }
      if   (cyt >  0.8) { eGFR <- 133 * (cyt/ 0.8)^-1.328 * 0.996^age }
      
    eGFR <- ifelse (gender=="Female",0.932 * eGFR, eGFR)
```

equation 3:
```r
    if (gender == "Female"){
      if   (crt <= 0.7 || cyt <= 0.8) { eGFR <- 130 * (crt/ 0.7)^-0.248 * (cyt/ 0.8)^-0.375 * 0.995^age }
      if   (crt <= 0.7 || cyt >  0.8) { eGFR <- 130 * (crt/ 0.7)^-0.248 * (cyt/ 0.8)^-0.711 * 0.995^age }
      if   (crt >  0.7 || cyt <= 0.8) { eGFR <- 130 * (crt/ 0.7)^-0.601 * (cyt/ 0.8)^-0.375 * 0.995^age }
      if   (crt >  0.7 || cyt >  0.8) { eGFR <- 130 * (crt/ 0.7)^-0.601 * (cyt/ 0.8)^-0.711 * 0.995^age }
    }
    if (gender == "Male"){
      if   (crt <= 0.9 || cyt <= 0.8) { eGFR <- 130 * (crt/ 0.7)^-0.207 * (cyt/ 0.8)^-0.375 * 0.995^age }
      if   (crt <= 0.9 || cyt >  0.8) { eGFR <- 130 * (crt/ 0.7)^-0.207 * (cyt/ 0.8)^-0.711 * 0.995^age }
      if   (crt >  0.9 || cyt <= 0.8) { eGFR <- 130 * (crt/ 0.7)^-0.601 * (cyt/ 0.8)^-0.375 * 0.995^age }
      if   (crt >  0.9 || cyt >  0.8) { eGFR <- 130 * (crt/ 0.7)^-0.601 * (cyt/ 0.8)^-0.711 * 0.995^age }
    }
      eGFR <- ifelse (race=="Black",1.159 * eGFR, eGFR)
```


##### References
 
ref for equation 0: [https://www.kidney.org/professionals/kdoqi/gfr_calculator]


##### See Also


##### Examples


##### GitHub link

[gfr_operator on GitHub](https://github.com/tercen/gfr_operator) 

## impute operator

##### Description
`impute` operator replaces NA with zero.

##### Usage

Input projection|.
:---|:---
`y-axis`        | is the input data for the imputation, per cell 

Output relations|.
:---|:---
`impute`        | numeric, a copy of the input data with NA replaces with zeros 

##### Details
The operator takes all the values of a cell and replaces it with the mean and if all values are NA then it is replaced with zero. The imputation is done per cell. There is one value calculated and returned for each of the input cell.

##### References


##### See Also


##### Examples


##### GitHub link

[impute_operator on GitHub](https://github.com/tercen/impute_operator) 

## IQR operator

##### Description

The `IQR` operator returns the interquartile range of a set of data points.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell 

Output relations|.
:---|:---
`iqr`        | numeric, median of the input data

##### Details

The operator takes all the values of a cell and returns the IQR value. The computation is done per cell and a single value is returned for each of the input cell.

##### References

https://en.wikipedia.org/wiki/Interquartile_range

##### See Also

[mean_operator](https://github.com/tercen/mean_operator)
[sd_operator](https://github.com/tercen/sd_operator)
[cv_operator](https://github.com/tercen/cv_operator)



##### GitHub link

[IQR_operator on GitHub](https://github.com/tercen/IQR_operator) 

## logfoldchange operator

##### Description
`logfoldchange` operator performs a fold change (i.e. ratio) caculation between two values.

##### Usage
Input projection|.
:---|:---
`x-axis`  | contains the grouping factor for the log2 fold change calculation, 
`y-axis` | values

Input parameter|.
:---|:---
`reverse`  | logical, to reverse the calculation, default is `FALSE`


Output relations|.
:---|:---
`logFC`| numeric, logfoldchange calculated per cell

##### Details
A `logfoldchange` operation is performed per cell. Each cell has values defined by the y-axis and seperated by the x-axis. The result of the logfoldchange is the log2 values where of the first is substrated by the second. If reverse is selected then the order of the substraction is changed.


##### References

##### See Also
[ratio](https://github.com/tercen/ratio_operator),[foldchange](https://github.com/tercen/foldchange_operator)
##### Examples


##### GitHub link

[logfoldchange_operator on GitHub](https://github.com/tercen/logfoldchange_operator) 

## log operator

##### Description
`log` operator performs a log of values

##### Usage
Input projection|.
:---|:---
`y-axis` | values to be logged

Input parameters|.
:---|:---
`base` | numeric, log base, default is 10

Output relations|.
:---|:---
`log`| numeric, log per data point

##### Details
A log of values is performed.


##### References
see the `base::log` function of the R package for the documentation, 


##### See Also

##### Examples




 
 


##### GitHub link

[log_operator on GitHub](https://github.com/tercen/log_operator) 

## max operator

##### Description

`max` operator returns the maximum of a set of data points.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell 

Output relations|.
:---|:---
`max`        | numeric, max of the input data

##### Details

The operator takes all the values of a cell and returns the value which is the maximum. The computation is done per cell (one value is returned for each input cell).

##### References

Based on the [max R function](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Extremes.html).

##### See Also

[product_operator](https://github.com/tercen/product_operator), [sum_operator](https://github.com/tercen/sum_operator)


##### GitHub link

[max_operator on GitHub](https://github.com/tercen/max_operator) 

## Mean imputation operator

##### Description

`mean_imputation` operator replaces missing values by the column mean.

##### Usage

Input projection|.
:---|:---
`row`        | factor, observations 
`column`     | factor, variables 
`y-axis`     | numeric, input data, per cell 

Output relations|.
:---|:---
`mean_imputed`        | numeric, measurements with imputed values

##### Details

The operator replaces missing values (`NA`) by the column mean.

##### References

See [Mean substitution on Wikipedia](https://en.wikipedia.org/wiki/Imputation_(statistics)#Mean_substitution).

##### See also

[impute_operator](https://github.com/tercen/impute_operator)


##### GitHub link

[mean_imputation_operator on GitHub](https://github.com/tercen/mean_imputation_operator) 

## mean operator

##### Description
`mean` operator computes the mean of a set of data points.

##### Usage

Input projection|.
:---|:---
`y-axis`        | is the input data for the mean, per cell 

Output relations|.
:---|:---
`mean`          | numeric, mean of the input values

##### Details
The operator takes all the values of a cell and calculates their mean. The computation is done per cell. There is one value calculated and returned for each of the input cell.

##### References


##### See Also

[product_operator](https://github.com/tercen/product_operator), [sum_operator](https://github.com/tercen/sum_operator)


##### Examples


##### GitHub link

[mean_operator on GitHub](https://github.com/tercen/mean_operator) 

## mean sd operator

##### Description
`mean sd` operator computes the mean and standard deviation of a set of data points.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell 

Output relations|.
:---|:---
`mean`       | numeric, mean of the input data
`sd`         | numeric, standard deviation of the input data

##### Details
The operator takes all the values of a cell and calculates their mean and standard deviation. The computation is done per cell. There are two value calculated and returned for each of the input cell.

##### References


##### See Also

[product_operator](https://github.com/tercen/product_operator), [sum_operator](https://github.com/tercen/sum_operator)


##### Examples


##### GitHub link

[mean_sd_operator on GitHub](https://github.com/tercen/mean_sd_operator) 

## Median operator

##### Description
`Median` operator returns the median of a set of data points.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell 

Output relations|.
:---|:---
`median`        | numeric, median of the input data

##### Details
The operator takes all the values of a cell and returns the value which is the median.The computation is done per cell. There is one value returned for each of the input cell.

##### References


##### See Also

[mean_operator](https://github.com/tercen/mean_operator)
##### Examples


##### GitHub link

[median_operator on GitHub](https://github.com/tercen/median_operator) 

#```R 
packrat::init(options = list(use.cache = TRUE)) 
```

##### GitHub link

[median_operator-1 on GitHub](https://github.com/tercen/median_operator-1) 

## negative operator

##### Description
`negative` operator performs a negative of values

##### Usage
Input projection|.
:---|:---
`y-axis` | values to be negated

Output relations|.
:---|:---
`negative`| numeric, negative per data point

##### Details
A negative of values is performed.


##### References


##### See Also

##### Examples




 
 


##### GitHub link

[negative_operator on GitHub](https://github.com/tercen/negative_operator) 

## Pairwise RMSD operator

##### Description

The `pairwise_RMSD` operator returns the Relative Mean Squared Deviation computed between pairs of variables.

##### Usage

Input projection|.
:---|:---
`row`        | factor, input variables 
`col`        | factor, observations 
`.y`        | numeric, measurements

Output relations|.
:---|:---
`rmsd`        | numeric, RMSD
`to`        | numeric, variable to be projected against the initial one for pairwise distance visualisation

##### Details

##### References

##### See Also

##### Examples


##### GitHub link

[pairwise_RMSD_operator on GitHub](https://github.com/tercen/pairwise_RMSD_operator) 

## pearson operator

##### Description
`pearson` operator performs a person correlation of two input sets of data per cell

##### Usage
Input projection|.
:---|:---
`x-axis`  | value of one group of data
`y-axis` | value of other group of data


Output relations|.
:---|:---
`cor`| numeric, pearson correlation calculated per cell
`pv`| numeric, p-value calculated per cell

##### Details
A pearson correlation is performed per cell where the two groups of data to be correlated are found on the `x-axis` and `y-axis`.
This operator is ideally suited as an operator for multiple pairwise projections in Tercen.


##### References
see the `base::cor.test` function of the R package for the documentation, 


##### See Also

##### Examples




 
 


##### GitHub link

[pearson_operator on GitHub](https://github.com/tercen/pearson_operator) 

## Percentile operator

##### Description
`percentile` operator returns the percentile of a set of data points.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell

Input parameters|.
:---|:---
`percentile` | numeric, the percentile to use, default is 0.01, 1% percentile

Output relations|.
:---|:---
`percentile`    | numeric, percentile of the input data

##### Details
The operator takes all the values of a cell and returns the precentile value. The computation is done per cell. There is one value returned for each of the input cell.

##### References


##### See Also

[product_operator](https://github.com/tercen/max_operator), [sum_operator](https://github.com/tercen/min_operator)


##### Examples


##### GitHub link

[percentile_operator on GitHub](https://github.com/tercen/percentile_operator) 

## Introduction

This is a template repository.

Use this template repository during the first step of developing a tercen operator (in R) on github.

An overview of steps for developing an operator are:

1. create a github repo
2. install tercen_studio
3. login to tercen_studio
4. git clone the newly created repo
5. start developing in R in tercen_studio
6. add R packages to the repo
7. push to the github repo
8. go to tercen and install the operator

For step 1, when creating the repo on github, you will notice the option to use a template repository, choose the `templateR_operator` repository and select it as the template repository.

After creation, you now have a new repository with all the convenient files for making a new operator (in R) for tercen.

Use `tercen_studio` to clone the new repository and start programming in `tercen_studio`

it includes the skeleton files 

* `main.R`
* `workspace.R`
* `operator.json`
* `README_template.md`
* `doc` directory

please remember to change the `README_template.md` to  `README.template.md`

inside the `doc` there is a `dev_commands.md` file which contains useful development command lines.


##### GitHub link

[read_VCF_operator on GitHub](https://github.com/tercen/read_VCF_operator) 

## RMSD operator

##### Description

`RMSD` operator returns the Relative Mean Square Deviation of two variables.

##### Usage

Input projection|.
:---|:---
`x-axis`        | numeric, input data, per cell 
`y-axis`        | numeric, input data, per cell 

Output relations|.
:---|:---
`rmsd`        | numeric, RMSD of the input data

##### Details

##### References

##### See Also

[lm_operator](https://github.com/tercen/lm_operator)

##### Examples


##### GitHub link

[RMSD_operator on GitHub](https://github.com/tercen/RMSD_operator) 

## Round operator

##### Description

`Round` operator implements different number rounding methods.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell

Output relations|.
:---|:---
`rounded`        | numeric, rounded input data



##### GitHub link

[round_operator on GitHub](https://github.com/tercen/round_operator) 

## Sample operator

##### Description
`Sample` operator returns a sample of the specified size from the set of data points using either with or without replacement.

##### Usage

Input projection|.
:---|:---
`y-axis`      | numeric, input data
`cols`        | numeric, observations, the sample factor(s) 

Input parameters|.
:---|:---
`size`   | numeric, the fraction to sample, default is 1 (100% percent)
`replace` | boolean, should replacement be used? , default is false (no replacement)

Output relations|.
:---|:---
`sample`        | numeric, sample of the input data

##### Details
The operator randomly selects columns (i.e. samples)

##### References
See the `sample` function in base R.


##### See Also

##### Examples


##### GitHub link

[sample_operator on GitHub](https://github.com/tercen/sample_operator) 

## scale operator

##### Description

`scale` operator performs a scaling of the data

##### Usage

Input projection|.
:---|:---
`row`   | represents the variables (e.g. channels, markers, genes)
`col`   | represents the observations (e.g. cells, samples, indviduals) 
`y-axis`| measurement value


Input parameters|.
:---|:---
`scale`   | logical, if scale is `TRUE` then scaling is done by dividing the (centered) row of x by their standard deviations if center is TRUE, and the root mean square otherwise. If scale is `FALSE`, no scaling is done.
`center`  | If center is `TRUE` then centering is done by subtracting the row means (omitting NAs) of x from their corresponding columns, and if center is `FALSE`, no centering is done.

Output relations|.
:---|:---
`scale`| numeric, per cell

##### Details

The operator is the `scale` function in base R.

##### References

See the `base::scale` function of the R package for more details.




##### GitHub link

[scale_operator on GitHub](https://github.com/tercen/scale_operator) 

## sd operator

##### Description
`sd` operator computes the standard deviation of a set of data points.

##### Usage

Input projection|.
:---|:---
`y-axis`        | is the input data for the sd, per cell 

Output relations|.
:---|:---
`sd`          | numeric, sd of the input values

##### Details
The operator takes all the values of a cell and calculates their standard deviation. The computation is done per cell. There is one value calculated and returned for each of the input cell.

##### References


##### See Also

[mean_operator](https://github.com/tercen/mean_operator), [sum_operator](https://github.com/tercen/sum_operator)


##### Examples



##### GitHub link

[sd_operator on GitHub](https://github.com/tercen/sd_operator) 

## Seqlen operator

##### Description
`Seqlen` operator creates a sequence annotation for a data series

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell 
`x-axis`        | numeric, input data, ordering of the data series

Output relations|.
:---|:---
`seq`         | numeric, sequence of the input data

##### Details
The operator takes all the values of a cell ordered by the 'x-axis'and gives a sequence number to each data point in the cell.

##### References


##### See Also

[topn_operator](https://github.com/tercen/topn_operator)

##### Examples


##### GitHub link

[seqlen_operator on GitHub](https://github.com/tercen/seqlen_operator) 

## Shift operator

##### Description
`shift` operator performs a shift by a constant value.

##### Usage
Input projection|.
:---|:---
`y-axis` | values as input to the shift operator

Input parameters|.
:---|:---
`constant` | numeric, the shift value, default is 0

Output relations|.
:---|:---
`shift`| numeric, output shift transformation per data point

##### Details
A shift by a constant value is performed to all data points.
```r
value + shift
```
##### References

##### See Also

##### Examples


##### GitHub link

[shift_operator on GitHub](https://github.com/tercen/shift_operator) 

## Setup packrat 

```R
packrat::init(options = list(use.cache = TRUE))
```

```R
shiny::runApp(port=3044, launch.browser = TRUE)
```

 







##### GitHub link

[shiny_boxplot_operator on GitHub](https://github.com/tercen/shiny_boxplot_operator) 

## shiny_docker_operator

```
https://github.com/tercen/shiny_docker_operator.git
```

## Build

```bash
VERSION=0.10.0.1
docker build -t tercen/shiny_docker_operator:$VERSION .
docker push tercen/shiny_docker_operator:$VERSION
git add -A && git commit -m "$VERSION" && git tag  $VERSION  && git push && git push :--tags
```
 

##### GitHub link

[shiny_docker_operator on GitHub](https://github.com/tercen/shiny_docker_operator) 

## Setup packrat 

```R
 
packrat::init(options = list(use.cache = TRUE))
   
 
```

# Shiny app

A simple shiny tercen operator :
 - display an histrogram
 - compute the mean
 
```
devtools::install_github("tercen/teRcen")

shiny::runApp(port=3044, launch.browser = FALSE)
```

 







##### GitHub link

[shiny_operator2 on GitHub](https://github.com/tercen/shiny_operator2) 

## signchange operator

##### Description
`signchange` operator negates the data value, i.e. sign changes

##### Usage
Input projection|.
:---|:---
`y-axis` | value of data to be sign changed


Output relations|.
:---|:---
`signchange`| numeric, the opposite sign of the value

##### Details
The `sigchange` operator changes the sign of the data by negating the value.


##### References

##### See Also

##### Examples




 
 


##### GitHub link

[signchange_operator on GitHub](https://github.com/tercen/signchange_operator) 

## Template Docker Operator

## For all operators

* Replace repository URL

* Replace version number in files

## For R operators

* isWebApp: false

## For Shiny operators

* isWebApp: true

## Build the image

```bash
VERSION=0.10.0.1
docker build -t tercen/shiny_docker_operator:$VERSION .
docker push tercen/shiny_docker_operator:$VERSION
git add -A && git commit -m "$VERSION" && git tag  $VERSION  && git push && git push :--tags
```


##### GitHub link

[template_docker_operator on GitHub](https://github.com/tercen/template_docker_operator) 

## Introduction

This is a template repository.

Use this template repository during the first step of developing a tercen operator (in R) on github.

An overview of steps for developing an operator are:

1. create a github repo
2. install tercen_studio
3. login to tercen_studio
4. git clone the newly created repo
5. start developing in R in tercen_studio
6. add R packages to the repo
7. push to the github repo
8. go to tercen and install the operator

For step 1, when creating the repo on github, you will notice the option to use a template repository, choose the `templateR_operator` repository and select it as the template repository.

After creation, you now have a new repository with all the convenient files for making a new operator (in R) for tercen.

Use `tercen_studio` to clone the new repository and start programming in `tercen_studio`

it includes the skeleton files 

* `main.R`
* `workspace.R`
* `operator.json`
* `README_template.md`
* `doc` directory

please remember to change the `README_template.md` to  `README.template.md`

inside the `doc` there is a `dev_commands.md` file which contains useful development command lines.


##### GitHub link

[template_R_operator on GitHub](https://github.com/tercen/template_R_operator) 

## topn operator

##### Description

`topn` operator returns  data points.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell 

Output relations|.
:---|:---
`elements`       | numeric, choosen elements of the input data

##### Details
The operator takes all the values of a cell and returns the top n elements. 

##### References


##### See Also


##### Examples


##### GitHub link

[topn_operator on GitHub](https://github.com/tercen/topn_operator) 

## ttest operator

##### Description
`ttest` operator performs a Student's t-test on the data

##### Usage
Input projection|.
:---|:---
`color`   | represents the groups to compare
`y-axis`| measurement value

Input parameters|.
:---|:---
`alternative`   | A character string specifying the alternative hypothesis, default is "two.sided"
`mu`  | A number indicating the true value of the mean (or difference in means if you are performing a two sample test), default 0.0
`var.equal`  |logical, indicating whether to treat the two variances as being equal. If `TRUE` then the pooled variance is used to estimate the variance otherwise the Welch (or Satterthwaite) approximation to the degrees of freedom is used, default `FALSE`
`conf.level`  |numeric, confidence level of the interval, default 0.95

Output relations|.
:---|:---
`pv`| numeric, p-value calculated per cell

##### Details
The operator is the `t.test` function in base R .


##### References
see the `base::t.test` function of the R package for the documentation, 


##### See Also
[anova](https://github.com/tercen/anova_operator),[rfImp](https://github.com/tercen/rfImp_operator)

##### Examples




##### GitHub link

[ttest_operator on GitHub](https://github.com/tercen/ttest_operator) 

## twogroupttest operator

##### Description
`twogroupttest` operator performs a Student's t-test on the data.

##### Usage
Input projection|.
:---|:---
`y-axis`  | measurement value
`x-axis`  | represents the two groups to compare
`color`   | represents the pairing

Input parameters|.
:---|:---
`reverse`   | logical, indicating whether to reverse the calculation on the x-axis, default `FALSE`
`paired`    | logical, indicating whether to perform pairing, default `FALSE`
`alternative`   | A character string specifying the alternative hypothesis, default is "two.sided"
`mu`  | A number indicating the true value of the mean (or difference in means if you are performing a two sample test), default 0.0
`var.equal`  |logical, indicating whether to treat the two variances as being equal. If `TRUE` then the pooled variance is used to estimate the variance otherwise the Welch (or Satterthwaite) approximation to the degrees of freedom is used, default `FALSE`
`conf.level`  |numeric, confidence level of the interval, default 0.95

Output relations|.
:---|:---
`p_value`| numeric, p-value calculated per cell

##### Details
The operator is the `t.test` function in base R .


##### References
see the `base::t.test` function of the R package for the documentation, 


##### See Also
[anova](https://github.com/tercen/anova_operator),[rfImp](https://github.com/tercen/rfImp_operator)

##### Examples




##### GitHub link

[twogroupttest_operator on GitHub](https://github.com/tercen/twogroupttest_operator) 

## Upper and lower bounds operator

##### Description

`upperandlowerbounds` operator computes an upper and lower bound values as a fraction of a given data point.

##### Usage

Input projection|.
:---|:---
`y-axis`             | is the input data for the multiplication per cell

Input parameters|.
:---|:---
`fraction`           | numeric, fraction value
`percentage`         | boolean, the relative values are returned as percentages

Output relations|.
:---|:---
`upperbound_absolute`| numeric, upper absolute bound value
`lowbound_absolute`  | numeric, lower absolute bound value
`upperbound_relative`| numeric, upper relative bound value
`lowbound_relative`  | numeric, lower relative bound value

##### Details

The operator takes the mean value of a cell and calculates an upper bound and a lowerbound.
The computation is done per cell. There are four values colculated and returned for each of the input cell.

The operator takes the mean value and calculates an upper bound by adding to it
```
  upperbound_absolute = value + (value * fraction)
  lowerbound_absolute = value + (value * fraction)
  
  upperbound_relative = (value * fraction)
  lowerbound_relative = (value * fraction)
```
Use this operator when wanting to determine upper and lower bounds. These generated bounds are usually used in a downstream data step for a graphics representation using grid lines which correspond to the boundary values (see horizontal grid lines feature)


##### GitHub link

[upperandlowerbounds_operator on GitHub](https://github.com/tercen/upperandlowerbounds_operator) 

## Setup packrat 

```R
packrat::init(options = list(use.cache = TRUE))
```

```R
shiny::runApp(port=3044, launch.browser = TRUE)
```

 







##### GitHub link

[venn_shiny_operator on GitHub](https://github.com/tercen/venn_shiny_operator) 

## Word count operator

##### Description
`Word count` operator count the occurences of each words in one or more documents.

##### Usage

Input projection|.
:---|:---
`row`        | is the documentId 

Output relations|.
:---|:---
`count`          | numeric, mean of the input values
`word`          | character, the word
`documentId`          | character, the id of the document

##### Details
The operator count the occurences of each words in one or more documents.

##### References


##### See Also


##### Examples


##### GitHub link

[wordcount_operator on GitHub](https://github.com/tercen/wordcount_operator)