# Basic operations 
 
## sample_operator  {-}

Description: `Sample` operator returns a sample of the specified size from the set of data points using either with or without replacement. 

Link: https://github.com/tercen/sample_operator 
 
## subtract_operator  {-}

Description: `subtract` operator computes the subtract of two data points. 

Link: https://github.com/tercen/subtract_operator 
 
## constant_operator  {-}

Description: `constant` operator allows for a value equal to a constant to be generated 

Link: https://github.com/tercen/constant_operator 
 
## product_operator  {-}

Description: `product` operator computes the product (i.e. multiplication) of a set of points. 

Link: https://github.com/tercen/product_operator 
 
## randomlabel_operator  {-}

Description: The `Random label` operator returns a random label per column. It allows one to subsample or downsample the data. 

Link: https://github.com/tercen/randomlabel_operator 
 
## topn_operator  {-}

Description: `topn` operator returns  data points. 

Link: https://github.com/tercen/topn_operator 
 
## annotation_operator  {-}

Description: NA 

Link: https://github.com/tercen/annotation_operator 
 
## wordcount_operator  {-}

Description: `Word count` operator count the occurences of each words in one or more documents. 

Link: https://github.com/tercen/wordcount_operator 
 
## ratio_operator  {-}

Description: `ratio` operator computes the ratio of two data points. 

Link: https://github.com/tercen/ratio_operator 
 
## seqlen_operator  {-}

Description: `Seqlen` operator creates a sequence annotation for a data series 

Link: https://github.com/tercen/seqlen_operator 
