# File import 
 

## AnnotatedDataFrame operator

##### Description

Converts a RData file containing an AnnotatedDataFrame object to a Tercen dataset.

##### Usage

Input projection|.
:---|:---
`documentId`        | is the documentId 

Output relations|.
:---|:---
`documentId`          | character, the id of the document

##### Details

An AnnotatedDataFrame consists of two parts. There is a collection of samples and the values of variables measured on those samples. There is also a description of each variable measured.

##### References

[AnnotatedDataFrame](https://rdrr.io/bioc/Biobase/man/class.AnnotatedDataFrame.html)


##### GitHub link

[readAnnotatedDataFrame_operator on GitHub](https://github.com/tercen/readAnnotatedDataFrame_operator) 

## readRDS operator

##### Description
`readRDS` operator imports rdsdata files

##### Usage

Input projection|.
:---|:---
`col`        | documentid, this the documentid of the file

Output relations|.
:---|:---
a tercen table   | tableid, for every tablid there is a documentid relation 

##### Details

The operator takes the documentIds (i.e. the RDS data file) and converts them to a tercen table.

##### References

see the `readRDS()` function in base R.

##### See Also

[readxls_operator](https://github.com/tercen/readxls_operator)
##### Examples


##### GitHub link

[readrds_operator on GitHub](https://github.com/tercen/readrds_operator) 

## Read excel file operator

##### Description

##### Usage

Input projection|.
:---|:---
`row`        | is the documentId 

Output relations|.
:---|:---
 

##### Details
The operator import excel document to tercen.

##### References


##### See Also


##### Examples


##### GitHub link

[readxl_operator on GitHub](https://github.com/tercen/readxl_operator) 

## Read FASTA operator

##### Description

`read_fasta` operator reads a FASTA file into Tercen.

##### Usage

Input projection|.
:---|:---
`col`        | factor, document ID

Output relations|.
:---|:---
`name`        | factor, sequence name
`position`    | numeric, position of amino or nucleic acid in the sequence
`letter`      | factor, letter corresponding to an amino or nucleic acid
`value`       | numeric, numeric value associated to an amino or nucleic acid

##### Details

This opeartor reads a FASTA file and returns a table with one row per sequence per letter. Columns correspond to the sequence `name` (extracted from identifier lines starting with `>`), `position` on the sequence (starting from `1` at the beginning of the sequence), the `letter` (corresponding to an amino or nucleic acid), and a `value` (corresponding to a numeric encoding of letters for visualisation purposes).

##### References

[FASTA format on Wikipedia](https://en.wikipedia.org/wiki/FASTA_format).

##### See Also

[msa_operator](https://github.com/tercen/msa_operator)


##### GitHub link

[read_fasta_operator on GitHub](https://github.com/tercen/read_fasta_operator) 

## FCS ZIP operator

##### Description

Transform zipped fcs files to tercen dataset.

##### Usage

Input projection|.
:---|:---
`documentId`        | is the documentId, a zip file

Output relations|.
:---|:---
`filename`          | character, the name of the fcs file
`channels`          | numeric, one variable per channel in the fcs file

##### Details

Extracts a ZIP archive of fcs files and tranforms them to tercen datasets.

Flow Cytometry Standard is a data file standard for the reading and writing of data from flow cytometry experiments.

##### References


##### See Also


##### Examples


##### GitHub link

[read_FCSzip_operator on GitHub](https://github.com/tercen/read_FCSzip_operator) 

## Read FCS operator

##### Description

`read_fcs` operator transforms FCS files to Tercen datasets.

##### Usage

Input projection|.
:---|:---
`documentId`        | is the documentId 

Output relations|.
:---|:---
`documentId`          | character, the id of the document

##### Details

Transforms FCS files to Tercen dataset. 

The Flow Cytometry Standard is a data file standard for the reading and writing of data from flow cytometry experiments.


##### GitHub link

[read_fcs_operator on GitHub](https://github.com/tercen/read_fcs_operator) 

## Read GMT operator

##### Description

`read_gmt` reads a GMT file containing a gene set annotation.

##### Usage

Input projection|.
:---|:---
`col`        | character, GMT document ID

Output relations|.
:---|:---
`set_name`        | character, gene set name
`set_description`        | character, gene set description
`set_genes`        | character, gene name

##### Details

GMT is a standard gene set format.

##### GitHub link

[read_gmt_operator on GitHub](https://github.com/tercen/read_gmt_operator) 

## STRAF to Tercen operator

##### Description

`straf2tercen` operator allows one to import STRAF input data into Tercen.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, input data, per cell 

Output relations|.
:---|:---
`median`        | numeric, median of the input data

##### Details
The operator takes all the values of a cell and returns the value which is the median.The computation is done per cell. There is one value returned for each of the input cell.

##### References


##### See Also

[mean_operator](https://github.com/tercen/mean_operator)
##### Examples


##### GitHub link

[straf2tercen_operator on GitHub](https://github.com/tercen/straf2tercen_operator)