# Statistical testing 
 

## ANOVA operator

##### Description

The `anova` operator performs an analysis of variance of the data.

##### Usage

Input projection|.
:---|:---
`color` | represents the groups to compare
`y-axis`| measurement value

Output relations|.
:---|:---
`pr`| numeric, p-value calculated per cell

##### Details

`anova` operator performs an analysis of variance of the data. The operator is based on the [anova R function](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/anova).

##### References

See [Analysis of variance on Wikipedia](https://en.wikipedia.org/wiki/Analysis_of_variance).

##### See Also

[ttest](https://github.com/tercen/ttest_operator), [rfImp](https://github.com/tercen/rfImp_operator)


##### GitHub link

[anova_operator on GitHub](https://github.com/tercen/anova_operator) 

## lm operator

##### Description

The `lm` operator performs a linear regression in Tercen.

##### Usage
Input projection|.
:---|:---
`y-axis`| measurement value
`x-axis`| explanatory value

Output relations|.
:---|:---
`intercept`| numeric, p-value calculated per cell
`slope`| numeric, p-value calculated per cell
`fit.x`| numeric, lowest and highest x values
`fit.y`| numeric, lowest and highest predicted y values

##### Details

The `lm` operator performs a linear regression on each cell.

##### References

See [Linear regression on Wikipedia](https://en.wikipedia.org/wiki/Linear_regression) and
`lm` [R function documentation](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lm).

##### See Also

[anova](https://github.com/tercen/anova_operator)



##### GitHub link

[lm_operator on GitHub](https://github.com/tercen/lm_operator) 

## t-test operator

##### Description

The `ttest` operator performs a Student's t-test on the data.

##### Usage

Input projection|.
:---|:---
`color`   | represents the groups to compare
`y-axis`| measurement value
`labels`   | represents the pairing

Input parameters|.
:---|:---
`alternative`   | A character string specifying the alternative hypothesis, default is "two.sided"
`paired`   | logical, indicating whether to perform pairing, default FALSE
`mu`  | A number indicating the true value of the mean (or difference in means if you are performing a two sample test), default 0.0
`var.equal`  |logical, indicating whether to treat the two variances as being equal. If `TRUE` then the pooled variance is used to estimate the variance otherwise the Welch (or Satterthwaite) approximation to the degrees of freedom is used, default `FALSE`
`conf.level`  |numeric, confidence level of the interval, default 0.95

Output relations|.
:---|:---
`pv`| numeric, p-value calculated per cell

##### Details

The operator is the `t.test` function in base R.

##### References

see the `base::t.test` function of the R package for the documentation, 

##### See Also

[anova](https://github.com/tercen/anova_operator), [rfImp](https://github.com/tercen/rfImp_operator)



##### GitHub link

[ttest_operator on GitHub](https://github.com/tercen/ttest_operator) 

## Two group t-test operator

##### Description

`twogroupttest` operator performs a Student's t-test on the data.

##### Usage

Input projection|.
:---|:---
`y-axis`  | measurement value
`x-axis`  | represents the two groups to compare
`color`   | represents the pairing

Input parameters|.
:---|:---
`reverse`   | logical, indicating whether to reverse the calculation on the x-axis, default `FALSE`
`paired`    | logical, indicating whether to perform pairing, default `FALSE`
`alternative`   | A character string specifying the alternative hypothesis, default is "two.sided"
`mu`  | A number indicating the true value of the mean (or difference in means if you are performing a two sample test), default 0.0
`var.equal`  |logical, indicating whether to treat the two variances as being equal. If `TRUE` then the pooled variance is used to estimate the variance otherwise the Welch (or Satterthwaite) approximation to the degrees of freedom is used, default `FALSE`
`conf.level`  |numeric, confidence level of the interval, default 0.95

Output relations|.
:---|:---
`p_value`| numeric, p-value calculated per cell

##### Details

The operator is the `t.test` function in base R.

##### References

See the `base::t.test` function of the R package for the documentation, 

##### See Also

[anova](https://github.com/tercen/anova_operator), [rfImp](https://github.com/tercen/rfImp_operator)




##### GitHub link

[twogroupttest_operator on GitHub](https://github.com/tercen/twogroupttest_operator)