# Data visualisation 
 

## Boxplot Shiny operator for Tercen

##### Description

The `Boxplot Shiny operator` is an operator to represent data as boxplots in Tercen.

##### Usage

Input projection|.
:---|:---
`y-axis`        | numeric, measurement to represent 
`row`           | factor, groups corresponding to different boxes along x axis
`column`        | factor (optional), groups corresponding to different plot panels
`colors`        | factor (optional), groups for corresponding to box and points coloring 

Output relations|.
:---|:---
`Operator view`        | view of the Shiny application

##### Details

The operator takes all the values of a cell and represents a boxplot. Depending on the assignment of rows, columns and colors in the Tercen projection, the layout will be different.

##### References

https://en.wikipedia.org/wiki/Box_plot


##### GitHub link

[boxplot_shiny_operator on GitHub](https://github.com/tercen/boxplot_shiny_operator) 

## Hierarchical clustering tree operator

##### Description

`clustering_tree` operator returns a hierarchical clustering tree to be projected in Tercen.

##### Usage

Input projection|.
:---|:---
`row`        | factor, variables to cluster
`col`        | factor, variables to cluster (`dist_to` variable from a `dist` operator) 
`y-axis`        | numeric, pairwise distance (`dist` variable from a `dist` operator)

Output relations|.
:---|:---
`presence`        | numeric, to be projected on y-axis
`tree_dim1`        | factor, to be projected on rows
`tree_dim2`        | factor, to be projected on columns
`tip_labels`        | factor, leaf labels, to be projected on rows



##### GitHub link

[clustering_tree_operator on GitHub](https://github.com/tercen/clustering_tree_operator) 

## Shiny Heatmap Tercen operator

##### Description

The `Shiny Heatmap operator` plots a clustered heatmap.

##### Usage

Input projection|.
:---|:---
`row`           | factor, variables
`col`           | factor, observations 
`y-axis`           | numeric, measurement (corresponding to the color on the heatmap) 

Output relations|.
:---|:---
`Operator view`        | view of the Shiny application

##### References

This operator is based on the [pheatmap R function](https://www.rdocumentation.org/packages/pheatmap/versions/1.0.12/topics/pheatmap).

##### See Also

[pairwise_distance_operator](https://github.com/tercen/pairwise_distance_operator), [hclust_operator](https://github.com/tercen/hclust_operator)


##### GitHub link

[heatmap_shiny_operator on GitHub](https://github.com/tercen/heatmap_shiny_operator) 

## Worldmap

```
https://github.com/tercen/worldmap_shiny_docker_operator.git
```
## Build

```bash
VERSION=0.1.0
docker build -t agouy/worldmap:$VERSION .
docker push agouy/worldmap:$VERSION
git add -A && git commit -m "$VERSION" && git tag -a $VERSION -m "++" && git push && git push :--tags
```


##### GitHub link

[worldmap_shiny_docker_operator on GitHub](https://github.com/tercen/worldmap_shiny_docker_operator) 

## Shiny World Map Tercen operator

##### Description

The `shiny_worldmap` allows one to plot markers on a world map using Tercen.

##### Usage

Input projection|.
:---|:---
`y-axis`| longitude (**decimal** coordinate)
`x-axis`| latitude (**decimal** coordinate)
`color`| measurement



##### GitHub link

[worldmap_shiny_operator on GitHub](https://github.com/tercen/worldmap_shiny_operator)