# Template 
 

## Shiny docker operator

##### Description

A simple example of a shiny docker operator.

```
https://github.com/tercen/shiny_docker_operator.git
```

##### Build

```bash
VERSION=0.10.0.1
docker build -t tercen/shiny_docker_operator:$VERSION .
docker push tercen/shiny_docker_operator:$VERSION
git add -A && git commit -m "$VERSION" && git tag  $VERSION  && git push && git push :--tags
```
 


##### GitHub link

[shiny_docker_operator on GitHub](https://github.com/tercen/shiny_docker_operator) 

## Template Docker Operator

The Template Docker operator is a template repository for the creation of docker operators in Tercen.

More information on how to develop such an operator can be found in the [Tercen app builder's guide](https://tercen.github.io/appbuilders-guide/).

Checklist before building the image:

* For all operators
    + Replace repository URL
    + Replace version number in files

* For R operators
    + isWebApp: false

* For Shiny operators
    + isWebApp: true

* Build the image

```bash
VERSION=0.10.0.1
docker build -t tercen/shiny_docker_operator:$VERSION .
docker push tercen/shiny_docker_operator:$VERSION
git add -A && git commit -m "$VERSION" && git tag  $VERSION  && git push && git push :--tags
```


##### GitHub link

[template_docker_operator on GitHub](https://github.com/tercen/template_docker_operator) 

## Template R operator for Tercen

The `Template R operator` is a template repository for the creation of R operators in Tercen. An overview of steps for developing an operator are:

1. create a github repo
2. install tercen_studio
3. login to tercen_studio
4. git clone the newly created repo
5. start developing in R in tercen_studio
6. add R packages to the repo
7. push to the github repo
8. go to tercen and install the operator

More information can be found in [Tercen app builder's guide](https://tercen.github.io/appbuilders-guide/).

Below is the operator README standard structure:

##### Description

The `Template R operator` is a template repository for the creation of R operators in Tercen. An overview of steps for developing an operator are:

##### Usage

Input projection|.
:---|:---
`x-axis`        | type, description 
`y-axis`        | type, description 
`row`           | type, description 
`column`        | type, description 
`colors`        | type, description 
`labels`        | type, description 

Output relations|.
:---|:---
`Operator view`        | view of the Shiny application

##### Details

Details on the computation.

##### See Also

[template_shiny_operator](https://github.com/tercen/template_shiny_operator)
, [template_docker_operator](https://github.com/tercen/template_docker_operator)



##### GitHub link

[template_R_operator on GitHub](https://github.com/tercen/template_R_operator) 

## Template Shiny operator for Tercen

##### Description

The `Template Shiny operator` is a template repository for the creation of Shiny operators in Tercen.

##### Usage

Input projection|.
:---|:---
`x-axis`        | type, description 
`y-axis`        | type, description 
`row`           | type, description 
`column`        | type, description 
`colors`        | type, description 
`labels`        | type, description 

Output relations|.
:---|:---
`Operator view`        | view of the Shiny application

##### Details

Details on the computation.

##### See Also

[template_R_operator](https://github.com/tercen/template_R_operator)


##### GitHub link

[template_shiny_operator on GitHub](https://github.com/tercen/template_shiny_operator)